---
title: "Diversity Washing Makes Things Worse"
date: "2015-12-07"
author: "Rachel Thomas"
categories: [inclusion]
image: "woc.jpg"
description: "Shallow, showy diversity efforts aren't just ineffective, they are actively harmful."
toc: true
---

## How Diversity Washing Hurts Diversity

It is painful watching tech companies known to be bad environments for women and people of color make shallow, showy attempts to rebrand themselves as valuing diversity. Perhaps you’re thinking, _Any effort towards diversity is a good thing, and there’s no harm in trying, right?_ Wrong. This is not just a triumph of style over substance; these efforts can harm the people they are purporting to help. For instance, research shows that many diversity programs [**reduce**](https://www.cfa.harvard.edu/cfawis/Dobbin_best_practices.pdf)  the number of Black women and Black men in management; diversity structures cause people to be [**less likely**](http://depts.washington.edu/silab/Documents/JPSP%20in%20press.pdf)  to believe women and people of color; and some forms of unconscious bias training [**increase bias**](http://www.nytimes.com/2014/12/07/opinion/sunday/adam-grant-and-sheryl-sandberg-on-discrimination-at-work.html?_r=0).

Since the following points have been covered thoroughly elsewhere, I’m going to take it as a given that:

1.  [Tech](http://www.theguardian.com/technology/2015/jun/25/facebook-diversity-report-black-white-women-employees) [has a](https://medium.com/tech-diversity-files/thought-on-diversity-part-2-why-diversity-is-difficult-3dfd552fa1f7) [diversity](http://www.forbes.com/sites/bonniemarcus/2015/08/12/the-lack-of-diversity-in-tech-is-a-cultural-issue/) [problem](https://drive.google.com/file/d/0B7mWRhOACwfSWlZ5Yy1JMkI4OWM/view?usp=sharing)
2.  [It’s](https://medium.com/@racheltho/if-you-think-women-in-tech-is-just-a-pipeline-problem-you-haven-t-been-paying-attention-cb7a2073b996) [not](http://www.cio.com/article/2998536/careers-staffing/where-s-the-diversity-look-at-your-culture-not-your-pipeline.html) [just](http://www.npr.org/sections/alltechconsidered/2015/07/26/426364306/more-than-a-pipeline-problem-in-search-of-diversity-in-silicon-valley) [the](http://techcrunch.com/2014/08/23/just-another-white-dude-writing-about-diversity/) [pipeline](http://www.fastcompany.com/3045989/strong-female-lead/the-pipeline-isnt-the-problem-dissecting-the-real-gender-bias-in-tech-pos) ([really](http://leanangry.tumblr.com/post/125716699460/your-pipeline-argument-is-bullshit?utm_content=buffer4e727))
3.  [Meritocracy](http://techcrunch.com/2015/04/02/kapors-2/) [is](https://medium.com/@jocelyngoldfein/techs-meritocracy-problem-a6e5e0a56157) [a](http://www.wired.com/2013/11/silicon-valley-isnt-a-meritocracy-and-the-cult-of-the-entrepreneur-holds-people-back/) [myth](http://carlos.bueno.org/2014/06/mirrortocracy.html)
4.  [Diversity](http://www.scientificamerican.com/article/how-diversity-makes-us-smarter/) [is a](http://www.citylab.com/work/2011/12/diversity-leads-to-economic-growth/687/) [good](http://www.catalyst.org/media/companies-more-women-board-directors-experience-higher-financial-performance-according-latest) [thing](http://www.npr.org/2014/03/21/292225798/does-diversity-on-research-team-improve-quality-of-science)

(If you’re unfamiliar with these ideas, please read the linked articles; I highly recommend them.) I very much want to see these problems fixed, but they need more than just a coat of PR-friendly paint. Any successful effort towards diversity and inclusion will need to involve comprehensive changes, ongoing self-reflection, and tackling hard problems, not just superficial, high-publicity, quick fixes.

The rest of this post will dig into what the research shows about ways that diversity programs can backfire. My next article will suggest some ideas for effective programs.

## The danger of diversity washing

[Researchers from U of Washington, UCLA, and UCSB](http://depts.washington.edu/silab/Documents/JPSP%20in%20press.pdf) showed that the mere presence of diversity policies, diversity training, and diversity awards cause white people to be **less likely to believe** racial discrimination exists and cause men to be **less likely to believe** gender discrimination exists, despite other data and evidence. Participants in one study read [a New York Times article](http://www.nytimes.com/2010/04/07/business/07gender.html) published as a class action lawsuit for gender discrimination against pharmaceutical giant Novartis went to trial. The twist was that half the participants were shown an article that included a sentence stating that _Working Mother_ magazine had chosen Novartis as one of the 100 best companies in the USA. This sentence was omitted from the article for the other half. Those that read the sentence about the_Working Mother_ accolade were **less likely** to believe that the female employees had a valid case against Novartis, even though the rest of the article remained the same.

The researchers conducted 6 variations of the study. In one version, white people read either a diversity statement, or a mission statement, for a fictional company. They were then shown data on comparative promotion rates by race, as well as an article about a Black employee filing suit for racial discrimination. Participants who had read the diversity statement were **less likely to believe** that discrimination had occurred and rated the Black employee **more negatively** (compared to those that read the mission statement, which did not mention diversity), even when the data showed clear racial differences. Other versions of the study provided differing data on hiring rates and salaries. In all versions, the presence of a diversity structure (such as diversity policies, diversity training, or diversity awards) caused white people to be less likely to believe racial discrimination and caused men to be less likely to believe gender discrimination.

This shows that the presence of diversity programs can hurt women and people of color by creating what the study’s authors call an _illusion of fairness_. Because of the **“diversity branding”**, people are less likely to believe that discrimination exists at that company, regardless of what the data shows. So the next time you see a tech company announce their shiny new diversity initiative with much fanfare, consider one impact: that the negative accounts of women and people of color that work at these companies will be disregarded even more often. This belief that the existence of diversity initiatives equals equality is just one way that such efforts can backfire. Next, let’s look at some real world data from the outcomes of diversity programs (it’s not what you would hope).

## What does data from diversity programs at over 700 companies reveal?

Harvard professor Frank Dobbin led a team of sociologists in [reviewing data from 708 companies](https://www.cfa.harvard.edu/cfawis/Dobbin_best_practices.pdf) to evaluate 7 different approaches to trying to increase the share of White women, Black women, and Black men in management, and found that **many programs were ineffective** and some diversity efforts even **made things worse**. Programs that targeted stereotypes through education and feedback, such as diversity training, were the least effective, and in some cases reduced diversity. The study found that diversity training was followed by a **7% decline** in the proportion of Black women in management. Diversity evaluations of managers were followed by an **8% decline** in Black men in management, although a 6% increase for White women. This is a particular issue when tech diversity efforts are often [limited only to recruiting White women](https://medium.com/this-is-hard/ffffff-diversity-1bd2b3421e8a#.802clcyks).

The most effective programs were “responsibility structures” such as diversity committees, diversity staff positions, and affirmative action plans. Professor Dobbin [stated](http://news.harvard.edu/gazette/2006/09.14/25-dobbin.html) that “if no one is specifically charged with the task of increasing diversity, then the buck inevitably gets passed ad infinitum. To increase diversity, executives must treat it like any other business goal.” Networking and mentoring produced modest positive effects. Diversity training was one of the **least effective** approaches. Dobbin [says](http://scholar.harvard.edu/dobbin/files/still_biased.pdf) that “even with best practices, you’re not going to get much of an effect. It doesn’t change what happens at work.”

Together with Alexandra Kalev of Tel Aviv University, Dobbin later expanded the research to 803 companies, and to include Asian and Hispanic employees (in addition to Black and White employees) in the aptly titled study “[Try and Make Me!: Why Corporate Diversity Training Fails](http://mitsloan.mit.edu/iwer/wp-content/uploads/2015/04/AATraining-3-16-2015-clean.pdf).” It is possible that the newer training programs currently in use by tech companies may end up being more effective than those reviewed in Dobbin’s study; however we should wait to see the evidence.

## Unconscious bias training can increase bias

Unconscious bias (for example, when people rate identical resumes [with a female](http://www.pnas.org/content/109/41/16474.full.pdf) or [traditionally African American name](http://www.chicagobooth.edu/capideas/spring03/racialbias.html) more negatively, as opposed to the same resume with a male or traditionally white name) is a very real problem; however just teaching people that unconscious bias exists does not eliminate it and can even increase bias. In [this NYTimes article](http://www.nytimes.com/2014/12/07/opinion/sunday/adam-grant-and-sheryl-sandberg-on-discrimination-at-work.html?_r=0), Sheryl Sandberg and Wharton professor Adam Grant summarize research that unconscious bias training can **increase bias**, depending on how it is communicated.

In one study from UVA and Washington University, managers read a job interview transcript after either being told either that: stereotypes are rare; or being told that: many people believe stereotypes. When participants were told **stereotypes were common** and that the candidate was female, they were **28% less likely** to hire her and judged her as 27% less likable (compared to the identical transcript with the candidate labeled as male). People may feel more comfortable believing stereotypes when they hear that they are commonly believed. Sandberg and Grant argue that the key is to instead communicate that biases are inaccurate, and that most people don’t want to discriminate.

## The Difficulty of Self-Reflection

Part of the problem with efforts to raise awareness of unconscious bias is that we are great at finding post-hoc justifications for our biases so we tend to see ourselves as immune to bias. Harvard Business School professor Francesca Gino, who has taught courses on biases and decision making to executives and MBA students, [states](https://hbr.org/2015/08/what-facebooks-anti-bias-training-program-gets-right) “most of my students easily recognize that their colleagues and friends are biased but generally don’t think they are themselves.” It is both easier to believe that other people discriminate, but not me, because I have good judgement, and easier to believe that other people experience discrimination, but not my coworker, because I see her flaws.

A [study](http://www.socialjudgments.com/docs/Uhlmann%20and%20Cohen%202005.pdf) from Yale researchers shows that perceiving yourself as objective is actually correlated with showing **even more bias**. [Researchers](http://dspace.mit.edu/openaccess-disseminate/1721.1/65884) from MIT and Indiana University found that company structures that explicitly promote meritocracy (compared to those that don’t) **show greater bias** against women. The 445 participants in the study all had managerial experience and were asked to evaluate employee profiles given a set of organizational core values (which included meritocracy in some cases but not others). Women were awarded **smaller bonuses than men** with equivalent performance reviews when the core values emphasized meritocracy.

Gender and racial biases aren’t just problems affecting the education system and other people’s companies; biases are affecting your company. It’s not just that other people need to change; we all need to change, and it’s an ongoing process.

## No Easy Fixes

I am not the first to express similar frustrations, although I have seen little coverage by tech journalists of this aspect of the issue. Erica Joy, an engineer at Slack, [wrote](https://storify.com/EricaJoy/realdiversitynumbers) that she is “tired of the ‘we hired this many’ and ‘we gave this many dollars to girls coding initiatives.’ None of those numbers accurately portray what the inside of a company looks like.” Darrell Jones III, head of business development at Clef, [explained](https://medium.com/two-factor-authenticity/what-s-a-quant-to-a-king-8c6d90ae415), “when we allow companies to simply ‘educate’ their employees or ‘spread awareness’ by publishing dismal diversity numbers, we let them off the hook.” Cate Huston, a former Google engineer and head of mobile development at Ride, [ranked](http://www.catehuston.com/blog/2014/10/01/male-allies-and-ghc/) classes of diversity problems from easy to extra hard, and, expressed her disappointment that Grace Hopper Conference (for women in computing) primarily focuses on “easy problems,” asking, “Is it just going to be a celebration of managing the easy things. Of crawling over that exceptionally low bar of sexist marketing materials. Of focusing on the pipeline rather than the woman who are already here.” Freada Kapor Klein, founder of the Level Playing Field Institute, [has observed that](http://techcrunch.com/2015/04/02/kapors-2/) “there is way too much money going to hackathons teaching privileged girls how to code without any tie-in to anything else… We’re mapping out all of the drop-off points so that as opposed to being the 400th person who funds a girls coding program, we can even out the dollars.” Indie game developer Veve Jaffe [wrote](https://modelviewculture.com/pieces/intel-at-indiecade-the-cost-of-diversity-in-games) of Intel’s diversity efforts, “my experience reflects a growing trend of corporations paying lip service to diversity — and collecting all of its PR benefits — while demanding unpaid work from underrepresented developers.”

This is not an argument against donating to girls coding initiatives, hosting hackathons for girls, or creating inclusive marketing materials (all are good things!), just a reminder that these won’t impact the biases the talented women and people of color already working at your company are currently facing. No donation is ever a substitute for the hard work of self-reflection and company-wide change. The “easy” changes are necessary, but they are not sufficient.

Similarly, collecting and sharing diversity data is a necessary step in determining if your current approach is working, but not something to celebrate on its own. It is just a means towards the end goal of creating an equitable and inclusive work environment. If the data shows your approach is not working, you need to change what you’re doing.

One of the results of the [research](https://campus.fsu.edu/bbcswebdav/institution/academic/social_sciences/sociology/Reading%20Lists/Stratification%20%28Gender%2C%20Race%2C%20and%20Class%29%20Copies%20of%20Articles%20from%202009/Kalev-ASR-2006.pdf) on data from 708 companies is that “new programs decoupled from everyday practice often have no impact” and that it is more effective to rethink hiring and promotion structures entirely. This is similar to what Dr. Klein has found working on diversity issues for over a decade; Klein [says](http://techcrunch.com/2015/04/02/kapors-2/) that having “engineering deeply involved in company diversity and inclusion efforts is critically important to getting it right and not having it be a side annoying thing.”

## Conclusion

This post is not an argument against diversity initiatives, but a reminder that diversity and inclusion aren’t automatically achieved when these programs are announced. We should all be on the lookout for concrete progress (not just raw hiring numbers, but also percentage of women and people of color in management and executive positions, salary parity, and retention rates), as well as for negative side effects. Any successful effort towards diversity and inclusion will need to involve ongoing self-reflection, comprehensive changes, and addressing hard problems. In my [next post](https://medium.com/tech-diversity-files/donations-and-women-in-tech-panels-are-not-a-diversity-strategy-do-better-c3c51022a916), I will write about examples of more substantial changes.

_Many thanks to Jeremy Howard for feedback on earlier drafts of this post._

_I further develop the ideas here in my next post about_ [_bullshit diversity strategies and some better ideas_](https://medium.com/tech-diversity-files/donations-and-women-in-tech-panels-are-not-a-diversity-strategy-do-better-c3c51022a916#.fryvrpoxv) _for enacting positive change. I later survey the research on why_ [_women are unable to advance in their careers_](https://medium.com/@racheltho/the-real-reason-women-quit-tech-and-how-to-address-it-6dfb606929fd#.u76jrfsys) _and offer concrete strategies to address this problem. You may also be interested in my post_ [_debunking the pipeline myth, which shares my personal story of wanting to leave the tech industry_](https://medium.com/tech-diversity-files/if-you-think-women-in-tech-is-just-a-pipeline-problem-you-haven-t-been-paying-attention-cb7a2073b996#.xvy0dd4wm)_, as well as practical tips._
